general {
    lock_cmd = hyprlock
    before_sleep_cmd = hyprlock
    after_sleep_cmd = hyprctl reload
}

# 5 minutes idle → lock screen
listener {
    timeout = 300
    on-timeout = hyprlock
}

# 5 minutes idle → turn display off
listener {
    timeout = 300
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

